---
title:  "Kickout"
output:
  flexdashboard::flex_dashboard:
    navbar:
    - title:  "Me"
      href:  "https://mltwelve.com/"
      icon:  "fa-home"
    theme:  yeti
runtime:  shiny
editor_options:
  markdown:
    wrap:  72
resource_files:
  - "Images/trampoline-2589684135.jpg"
---

```{r setup, include=FALSE}
library(DT)
library(reactable)
library(dplyr)
library(flexdashboard)
library(shiny)
library(readr)
library(lubridate)
library(ggplot2)
library(plotly)
library(shinyWidgets)
library(tidyr)
library(reactablefmtr)
library(sparkline)

# Knitr options
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r load_data, include=FALSE}

# Source the script that generates the 'events' dataset
events <- read_csv("Dataout/all_events.csv")


 #events <-  read_csv("https://raw.githubusercontent.com/KirstinLyon/jump_metrics/refs/heads/main/Dataout/all_events.csv")
 
 start_data <- events  |> 
  mutate(Year = lubridate::year(Date)) |> 
  select(Year, Date, Event, Event_Year, Competition, Competitor, Birth_Year,Country, Club, Stage,
         Rank, Total, Mark, Elements, Execution, T, D, H, is_complete)  


compact_data <- start_data 

update_raw_data <- reactive({
  compact_data
})

detailed_data <- events |> 
  select(Date, Event,Event_Year, Competition, Competitor, Country, Club, Stage, Total, Mark, Elements, Execution, T, D, H,
         s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, l, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, is_complete) 


update_detailed_data <- reactive({
  detailed_data
})


score_data <- events |> 
  select(Date, Event,Event_Year, Competition, Rank, Competitor, Country, Club, Stage, Total, Mark, Elements, Execution, T, D, H, is_complete) 

update_score_data <- reactive({
  score_data
})
 
 
 
```



```{r child1, child='Markdown/1_intro.Rmd', eval = FALSE}
```

```{r child2, child='Markdown/event.Rmd', eval = FALSE}
```

```{r child3, child='Markdown/2_indiv_trend.Rmd', eval = FALSE}
```

```{r child4, child='Markdown/3_indiv_detail.Rmd', eval = TRUE}
```

```{r child5, child='Markdown/raw_data.Rmd', eval = FALSE}
```

