---
title: "Individual Trends"
output:
  flexdashboard::flex_dashboard:
    theme: yeti
runtime: shiny
editor_options:
  markdown:
    wrap: 72
---
# Competitor Overview 

## Column {.sidebar}

This dashboard displays the results for an individual competitor. Use the provided filters to customise the data and update the view according to your preferences.

```{r}


sorted_club <- sort(unique(start_data$Club))

selectInput('Club', 'Club',
            choices = sorted_club,
            selected = "KTK")

selectInput('Competitor', 'Competitor', choices = NULL)


pickerInput(
  inputId = "is_complete",
  label = "Skills Complete:",
  choices = unique(start_data$is_complete),
  selected = "Complete",
  options = list(
    `actions-box` = TRUE
  ),
  multiple = TRUE
)

pickerInput(
  inputId = "Stage",
  label = "Select Stage(s):",
  choices = unique(start_data$Stage),
  selected = c("Final", "Qualification_2"),
  options = list(
    `actions-box` = TRUE,
    `selected-text-format` = "count > 2"
  ),
  multiple = TRUE
)

# Server Logic (updated)
observeEvent(input$Club, {
  if (input$Club != "") {
    filtered_data <- start_data |> filter(Club == input$Club)
    updateSelectInput(session, 'Competitor', choices = sort(unique(filtered_data$Competitor)))
  } else {
    updateSelectInput(session, 'Competitor', choices = NULL)
  }
})

observeEvent(input$Competitor, {
  if (input$Competitor != "") {
    filtered_data <- start_data |> filter(Competitor == input$Competitor)
    updatePickerInput(session, 'is_complete', 
                      choices = sort(unique(filtered_data$is_complete)), 
                      selected = "Complete")
    updatePickerInput(session, 'Stage', 
                      choices = sort(unique(filtered_data$Stage)), 
                      selected = c("Final", "Qualification_2"))
  } else {
    updatePickerInput(session, 'is_complete', 
                      choices = unique(start_data$is_complete), 
                      selected = "Complete")
    
    updatePickerInput(session, 'Stage', 
                      choices = unique(start_data$Stage), 
                      selected = c("Final", "Qualification_2"))
  }
})


```

## Column {data-width="200"}

```{r}

# Use a div with a specific height to create space
div(style = "height: 24px;")  # Adjust the height as needed

# Text output with dynamic content and inline styles
div(style = "font-size: 24px; font-weight: bold;", textOutput("competitorLabel"))
# Server logic to update the text output
output$competitorLabel <- renderText({
  selected_competitor <- input$Competitor
  if (selected_competitor != "") {
    paste(selected_competitor)
  } else {
    "No Competitor selected"
  }
})
```

### Execution

```{r}

renderPlot({
  update_raw_data() |> 
    filter(
      Stage %in% input$Stage,
      Competitor == input$Competitor,
      is_complete %in% input$is_complete)  |>
    ggplot(aes(x = Date, y = Execution, colour = Stage)) +
    geom_line(linewidth = 0.95) +
    geom_point(size = 3) +  # This adds dots for each data point
    scale_color_hue(direction = 1) +
    labs( y = "Execution") +
    theme_minimal() +
    theme(legend.position = "top", legend.justification = "right") +
    expand_limits(y = 0)  # This one line forces y-axis to include 0
})
```

### Time of Flight (Seconds)

```{r}
renderPlot({
  update_raw_data() |> 
    filter(
      Stage %in% input$Stage,
      Competitor == input$Competitor,
      is_complete %in% input$is_complete)  |>
    ggplot(aes(x = Date, y = T, colour = Stage)) +
    geom_line(linewidth = 0.95) +
    geom_point(size = 3) +  # This adds dots for each data point
    scale_color_hue(direction = 1) +
    labs(y = "Time of Flight (S)") +
    theme_minimal() +
    theme(legend.position = "top", legend.justification = "right")+
    expand_limits(y = 0)  # This one line forces y-axis to include 0
})
```


### Difficulty

```{r}
renderPlot({
  update_raw_data() |> 
    filter(
      Stage %in% input$Stage,
      Competitor == input$Competitor,
      is_complete %in% input$is_complete)  |>
    ggplot(aes(x = Date, y = D, colour = Stage)) +
    geom_line(linewidth = 0.95) +
    geom_point(size = 3) +  # This adds dots for each data point
    scale_color_hue(direction = 1) +
    labs( y = "Difficulty") +
    theme_minimal() +
    theme(legend.position = "top", legend.justification = "right") +
    expand_limits(y = 0)  # This one line forces y-axis to include 0
})
```


### Horizontal Displacement

```{r}
renderPlot({
  update_raw_data() |> 
    filter(
      Stage %in% input$Stage,
      Competitor == input$Competitor,
      is_complete %in% input$is_complete)  |>
    ggplot(aes(x = Date, y = H, colour = Stage)) +
    geom_line(linewidth = 0.95) +
    geom_point(size = 3) +  # This adds dots for each data point
    scale_color_hue(direction = 1) +
    labs(y = "Horizontal Displacement") +
    theme_minimal() +
    theme(legend.position = "top", legend.justification = "right")+
    expand_limits(y = 0)  # This one line forces y-axis to include 0
})
```
## Column 

```{r}
div(style = "height: 55px;")  # Adjust the height as needed
textOutput("competitorLabel_1")

output$competitorLabel_1 <- renderText({
  paste("")  # This will render as empty text
})
```
###

```{r}
renderReactable({
  # Filter and prepare data
  plot_data <- score_data %>%
    filter(
      Competitor == input$Competitor,
      Stage %in% input$Stage,
      is_complete %in% input$is_complete 
    ) %>%
    select(-c(Event_Year, is_complete, Country, Club, Competitor, Total)) |> 
    select(Date, Event, Competition, Stage, everything()) |> 
    arrange(desc(Date), Stage) 
  
  reactable(
    plot_data,
    defaultColDef = colDef(
      headerStyle = list(background = "#f7f7f7"),
      style = list(fontSize = "0.9em"),
      align = "left"
    ),
    columns = list(
      Execution = colDef(
        
        cell = reactablefmtr::data_bars(
          data = plot_data,
          fill_color = "#e0e0e0",
          background = "transparent",
          text_position = "inside-base",
          min_value = 0,
          max_value = 22,
          number_fmt = function(x) sprintf("%.1f", x)
        )
      ),
      T = colDef(
        cell = reactablefmtr::data_bars(
          data = plot_data,
          fill_color = "#e0e0e0",
          background = "transparent",
          text_position = "inside-base",
          min_value = 0,
          max_value = 22,
          number_fmt = function(x) sprintf("%.1f", x)
        )
      ),
      H = colDef(
        cell = reactablefmtr::data_bars(
          data = plot_data,
          fill_color = "#e0e0e0",
          background = "transparent",
          text_position = "inside-base",
          min_value = 0,
          max_value = 22,
          number_fmt = function(x) sprintf("%.1f", x)
        )
      ),
      D = colDef(
        cell = reactablefmtr::data_bars(
          data = plot_data,
          fill_color = "#e0e0e0",
          background = "transparent",
          text_position = "inside-base",
          min_value = 0,
          max_value = 22,
          number_fmt = function(x) sprintf("%.1f", x)
        )
      )
    ),
    highlight = TRUE,
    bordered = TRUE,
    pagination = TRUE,
    defaultPageSize = 15
  )
})


```