name: Update Kickout Data

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          echo "Installing required packages..."
          R -e "install.packages(c('dplyr', 'readr', 'stringr', 'remotes'))"
     
      - name: Install kickout package
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Installing kickout package from GitHub..."
          R -e "remotes::install_github('kirstinlyon/kickout', 
                                      ref = 'main', 
                                      auth_token = '$GITHUB_PAT', 
                                      force = TRUE, 
                                      verbose = TRUE)"

      - name: Fetch and update data
        run: Rscript Scripts/fetch_data.R

      - name: Commit and push changes
        env:
          KICKOUT_AUTOMATION_TOKEN: ${{ secrets.KICKOUT_AUTOMATION_TOKEN }}
        run: |
          git config --global user.email "kirstin@mltwelve.com"
          git config --global user.name "KirstinLyon"
          git add Dataout/*.csv
          git commit -m "Update kickout data"
          git push https://${{ secrets.KICKOUT_AUTOMATION_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
